### ISSUE TITLE
Make detectCCType publicly accessible

### ISSUE THREAD

**Issue by Gintasz** [simformsolutions/flutter_credit_card#20]
On 0.1.3 detectCCType is not publicly accessible and there seems to be no method to detect card type by card number using your library even though the method is already in the library.

**Comment by Gintasz** [comment]
30secs after I posted this, I found there is another 3rd party library for this... https://pub.dev/packages/credit_card_type_detector

**Comment by parcool** [comment]
@Gintasz So how did you solve this problem? I'm encountering the same issue now, and I want to customize its 'detectCCType'. What should I do? For example, how can I integrate the library you mentioned into this?
