### ISSUE TITLE
ThemeData not applied to Credit Card Form

### ISSUE THREAD

**Issue by drkhannah** [simformsolutions/flutter_credit_card#3]
Hello, thanks for making this its really cool.

But I have ThemeData in my app that includes inputDecorationTheme for all inputs in my app

but this package doesn't use my theme data

is this a feature that needs to be created in this package, or is there a way for me to override the packages input decorations with my app's ThemeData

**Comment by simformsolutions** [comment]
Hi @drkhannah  , Thanks for using this. 
we've added `themeColor` property but yes  apply ThemeData as a default setting would be good idea, we're working on it. Will post update here as soon as it done.

**Comment by simformsolutions** [comment]
@drkhannah ThemeData applied in version `0.1.3 ` Please update the package to use this feature.
